### ISSUE TITLE
Can't open project after recent commits

### ISSUE THREAD

**Issue by JakeChampion** [cwhite92/Plymouth-Entrepreneurs-Society#1]
```
Warning: _cake_core_ cache was unable to write 'cake_dev_en-us' to File cache in /Users/jakechampion/Sites/ISAD234/lib/Cake/Cache/Cache.php on line 309

Warning: /Users/jakechampion/Sites/ISAD234/app/tmp/cache/persistent/ is not writable in /Users/jakechampion/Sites/ISAD234/lib/Cake/Cache/Engine/FileEngine.php on line 336

Fatal error: Uncaught exception 'CacheException' with message 'Cache engine _cake_core_ is not properly configured.' in /Users/jakechampion/Sites/ISAD234/lib/Cake/Cache/Cache.php:165 Stack trace: #0 /Users/jakechampion/Sites/ISAD234/lib/Cake/Cache/Cache.php(135): Cache::_buildEngine('_cake_core_') #1 /Users/jakechampion/Sites/ISAD234/app/Config/core.php(272): Cache::config('_cake_core_', Array) #2 /Users/jakechampion/Sites/ISAD234/lib/Cake/Core/Configure.php(76): include('/Users/jakecham...') #3 /Users/jakechampion/Sites/ISAD234/lib/Cake/bootstrap.php(163): Configure::bootstrap(true) #4 /Users/jakechampion/Sites/ISAD234/app/webroot/index.php(82): include('/Users/jakecham...') #5 {main} thrown in /Users/jakechampion/Sites/ISAD234/lib/Cake/Cache/Cache.php on line 165
```

**Comment by cwhite92** [comment]
Just removed .gitignore from the repo and recommitted tmp files, should be fixed now.

**Comment by JakeChampion** [comment]
Ill check later if it works and will see which temp files are not required
for git by looking at the cake php forums

**Comment by cwhite92** [comment]
Cake comes with a .gitignore in the package with the following entries:

```
/app/Config
/app/tmp
/lib/Cake/Console/Templates/skel/tmp/
/plugins
/vendors
/build
/dist
.DS_Store
/tags
```

**Comment by JakeChampion** [comment]
.gitignore was added, just forgot to close the issue.
